"use client";

import { QUIZ_CODE_LENGTH } from '@/lib/quiz';
import useExamControllerState from '@/app/hooks/useExamControllerState';
import useExamControllerCore from '@/app/hooks/useExamControllerCore';
import useExamJoinWiring from '@/app/hooks/useExamJoinWiring';
import useExamSessionOrchestration from '@/app/hooks/useExamSessionOrchestration';
import useExamSetupOrchestration from '@/app/hooks/useExamSetupOrchestration';
import useExamSelectionAndDerived from '@/app/hooks/useExamSelectionAndDerived';
import useExamClearStorage from '@/app/hooks/useExamClearStorage';
import useExamMeta from '@/app/hooks/useExamMeta';
import useExamPublicApi from '@/app/hooks/useExamPublicApi';
import useExamPublicPayload from '@/app/hooks/useExamPublicPayload';
import useExamResetActions from '@/app/hooks/useExamResetActions';
import { PREPARING_STEP, STORAGE_KEYS, TIME_LIMIT_OPTIONS } from '@/app/hooks/examControllerConstants';

declare global {
  interface Window {
    __retryCategoryFetch?: () => Promise<void>;
  }
}

export default function useExamPageController() {
  const {
    userName,
    setUserName,
    mapels,
    setMapels,
    babs,
    setBabs,
    subBabs,
    setSubBabs,
    availableMapels,
    setAvailableMapels,
    availableBabs,
    setAvailableBabs,
    availableSubBabs,
    setAvailableSubBabs,
    questionCount,
    setQuestionCount,
    step,
    setStep,
    current,
    setCurrent,
    sessionId,
    setSessionId,
    totalQuestions,
    setTotalQuestions,
    currentQuestion,
    setCurrentQuestion,
    answers,
    setAnswers,
    score,
    setScore,
    saved,
    setSaved,
    saving,
    setSaving,
    isRestored,
    setIsRestored,
    isLoading,
    setIsLoading,
    setFetchError,
    startTime,
    setStartTime,
    endTime,
    setEndTime,
    gameMode,
    setGameMode,
    saveFailed,
    setSaveFailed,
    lives,
    setLives,
    showSurrenderConfirm,
    setShowSurrenderConfirm,
    feedbackResult,
    setFeedbackResult,
    recapData,
    setRecapData,
    timeLimit,
    setTimeLimit,
    expiresAt,
    setExpiresAt,
    timeLeftDisplay,
    setTimeLeftDisplay,
    examMode,
    setExamMode,
    doubtFlags,
    setDoubtFlags,
    showNavPopup,
    setShowNavPopup,
    showSubmitConfirm,
    setShowSubmitConfirm,
    scheduledExamTitle,
    setScheduledExamTitle,
    isScheduledExam,
    setIsScheduledExam,
    scheduledTimeLimitMinutes,
    setScheduledTimeLimitMinutes,
  } = useExamControllerState();

  const clearStorage = useExamClearStorage();

  const total = totalQuestions;

  const {
    isSurvival,
    isStandard,
  } = useExamControllerCore({
    modeFlagsArgs: {
      gameMode,
      examMode,
    },
    securityStep: step,
    storageSyncArgs: {
      storageKeys: STORAGE_KEYS,
      isRestored,
      userName,
      step,
      current,
      answers,
      sessionId,
      totalQuestions,
      mapels,
      babs,
      subBabs,
      startTime,
      gameMode,
      lives,
      score,
      expiresAt,
      timeLimit,
      examMode,
      doubtFlags,
    },
  });

  const {
    hasAnswerSelected,
    selectAnswer,
    mapelsLabel,
    babsLabel,
    subBabsLabel,
    formattedDuration,
    answeredCount,
  } = useExamSelectionAndDerived({
    answerSelectionArgs: {
      answers,
      current,
      total,
      setAnswers,
    },
    derivedValuesArgs: {
      mapels,
      babs,
      subBabs,
      availableMapels,
      availableBabs,
      availableSubBabs,
      startTime,
      endTime,
      current,
      recapData,
    },
  });

  useExamSetupOrchestration({
    bootstrapArgs: {
      storageKeys: STORAGE_KEYS,
      setFetchError,
      setAvailableMapels,
      setMapels,
      setIsLoading,
      setUserName,
      setIsRestored,
      setSessionId,
      setTotalQuestions,
      setBabs,
      setSubBabs,
      setGameMode,
      setExamMode,
      setLives,
      setScore,
      setDoubtFlags,
      setStartTime,
      setExpiresAt,
      setTimeLimit,
      setAnswers,
      setCurrent,
      setStep,
      setCurrentQuestion,
    },
    categoryOptionsArgs: {
      mapels,
      babs,
      setAvailableBabs,
      setBabs,
      setAvailableSubBabs,
      setSubBabs,
    },
  });

  const {
    goToStep,
    startExam,
    endSession,
    goToQuestion,
    nextQuestion,
    skipQuestion,
    surrender,
    restart,
  } = useExamSessionOrchestration({
    autoSaveArgs: {
      userName,
      total,
      endTime,
      saved,
      sessionId,
      gameMode,
      setSaving,
      setScore,
      setTotalQuestions,
      setRecapData,
      setSaved,
      setSaveFailed,
      clearStorage,
    },
    lifecycleArgs: {
      userName,
      mapels,
      babs,
      subBabs,
      gameMode,
      questionCount,
      timeLimit,
      sessionId,
      current,
      answers,
      isSurvival,
      setIsLoading,
      setSessionId,
      setTotalQuestions,
      setAnswers,
      setDoubtFlags,
      setCurrent,
      setExpiresAt,
      setCurrentQuestion,
      setLives,
      setScore,
      setStep,
      setStartTime,
      setEndTime,
      setGameMode,
      setExamMode,
      setSaved,
      setSaveFailed,
      setRecapData,
      clearStorage,
      preparingStep: PREPARING_STEP,
    },
    progressionArgs: {
      sessionId,
      current,
      total,
      answers,
      currentQuestion,
      gameMode,
      isSurvival,
      feedbackResult,
      lives,
      setIsLoading,
      setCurrentQuestion,
      setCurrent,
      setShowNavPopup,
      setFeedbackResult,
      setScore,
      setLives,
    },
    expiryTimerArgs: {
      step,
      expiresAt,
      sessionId,
      answers,
      current,
      gameMode,
      setEndTime: (value) => setEndTime(value),
      setStep: (value) => setStep(value),
      setSaving: (value) => setSaving(value),
      setScore: (value) => setScore(value),
      setTotalQuestions: (value) => setTotalQuestions(value),
      setRecapData: (value) => setRecapData(value),
      setSaved: (value) => setSaved(value),
      setSaveFailed: (value) => setSaveFailed(value),
      setTimeLeftDisplay: (value) => setTimeLeftDisplay(value),
      clearStorage,
    },
  });

  const {
    joinState,
    setIsJoinModalOpen,
    handleJoinQuiz,
    handleQuizCodeChange,
    closeJoinModal,
  } = useExamJoinWiring({ quizCodeLength: QUIZ_CODE_LENGTH });

  const resetActions = useExamResetActions({
    surrender,
    restart,
  });

  const meta = useExamMeta({
    preparingStep: PREPARING_STEP,
    timeLimitOptions: TIME_LIMIT_OPTIONS,
    quizCodeLength: QUIZ_CODE_LENGTH,
  });

  const payload = useExamPublicPayload({
    state: {
      userName,
      mapels,
      babs,
      subBabs,
      availableMapels,
      availableBabs,
      availableSubBabs,
      questionCount,
      step,
      current,
      sessionId,
      totalQuestions,
      total,
      currentQuestion,
      answers,
      score,
      saved,
      saving,
      isRestored,
      isLoading,
      startTime,
      endTime,
      gameMode,
      saveFailed,
      lives,
      showSurrenderConfirm,
      feedbackResult,
      recapData,
      timeLimit,
      expiresAt,
      timeLeftDisplay,
      isJoinModalOpen: joinState.isJoinModalOpen,
      quizCode: joinState.quizCode,
      isCheckingCode: joinState.isCheckingCode,
      codeError: joinState.codeError,
      isSurvival,
      examMode,
      doubtFlags,
      showNavPopup,
      showSubmitConfirm,
      isStandard,
      hasAnswerSelected,
      mapelsLabel,
      babsLabel,
      subBabsLabel,
      formattedDuration,
      answeredCount,
      canJoinQuiz: joinState.canJoinQuiz,
      normalizedQuizCodeLength: joinState.normalizedQuizCodeLength,
      scheduledExamTitle,
      isScheduledExam,
      scheduledTimeLimitMinutes,
    },
    setters: {
      setUserName,
      setMapels,
      setBabs,
      setSubBabs,
      setQuestionCount,
      setStep,
      setLives,
      setScore,
      setGameMode,
      setExamMode,
      setShowNavPopup,
      setShowSubmitConfirm,
      setShowSurrenderConfirm,
      setDoubtFlags,
      setIsJoinModalOpen,
      setTimeLimit,
      setSessionId,
      setTotalQuestions,
      setExpiresAt,
      setStartTime,
      setAnswers,
      setCurrent,
      setCurrentQuestion,
      setEndTime,
      setRecapData,
      setSaved,
      setScheduledExamTitle,
      setIsScheduledExam,
      setScheduledTimeLimitMinutes,
    },
    actions: {
      goToStep,
      startExam,
      selectAnswer,
      endSession,
      goToQuestion,
      nextQuestion,
      skipQuestion,
      surrender: resetActions.surrender,
      restart: resetActions.restart,
      handleJoinQuiz,
      handleQuizCodeChange,
      closeJoinModal,
    },
  });

  return useExamPublicApi({
    meta,
    payload,
  });
}
